### ISSUE TITLE
Version 1.1

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm-setup#12]
Is anyone maintaining this? omnia is building something called version 1.1 from git hash fc94b50 but I can't tell if this is an official release or not, or if we should continue building this.

**Comment by peastman** [comment]
Yes, that's the current release.

**Comment by peastman** [comment]
There already is one.  https://github.com/omnia-md/conda-recipes/blob/master/openmm-setup/meta.yaml#L7

**Comment by peastman** [comment]
I created the github release for it.

**Comment by jchodera** [comment]
Thanks!
